version: '3.8'
env_file:
  - .env
services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: tianlong
      MYSQL_USER: tianlong
      MYSQL_PASSWORD: tianlong123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
    volumes:
      - es_data:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  consul:
    image: consul:1.9
    command: 'agent -dev -client=0.0.0.0'
    ports:
      - '8500:8500'
    volumes:
      - consul_data:/consul/data

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - '6831:6831/udp'
      - '16686:16686'

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: tianlong
      MYSQL_PASSWORD: tianlong123
      MYSQL_DATABASE: tianlong
      MONGO_URI: mongodb://mongodb:27017/tianlong
    depends_on:
      - mysql
      - mongodb
      - redis
    command: npm run start:dev

  worker:
    build: ./backend
    command: npm run start:worker
    depends_on:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: node dist/main.js

volumes:
  mysql_data:
  mongo_data:
  redis_data:
  es_data:
  consul_data:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - redis
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=tianlong
      - DB_PASSWORD=tianlong123
      - DB_DATABASE=tianlong
