
FROM node:18 as build-stage
WORKDIR /app
COPY ../frontend .
RUN npm install && npm run build

FROM nginx:stable-alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
