
version: '3.8'
services:
  backend:
    build:
      context: ./docker
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./docker
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
